on:
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install packages etc
        run: |
          npm i
          npx lerna bootstrap
          npx lerna run build
      - name: Create local changes
        run: |
          npm run docs
      - name: Commit files
        run: |
          git config --local user.email "goldrenard@gmail.com"
          git config --local user.name "Caramel <goldrenard@gmail.com>"
          git add -A
          git commit -m "org(docs): generating docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}